services:
  user-db:
    image: postgres:14.1-alpine
    container_name: user-db
    mem_reservation: 256m
    mem_limit: 512m
    cpus: 0.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=yt_airline_user_db
    ports:
      - '3302:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yt_airline_user_db -h localhost -p 5432"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - "./volumes/db/data/userdb:/var/lib/postgresql/data"
    networks:
      - airline-microservice
  aireline-core-db:
    image: postgres:14.1-alpine
    container_name: aireline-core-db
    mem_reservation: 256m
    mem_limit: 512m
    cpus: 0.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=yt_airline_core_db
    ports:
      - '3303:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yt_airline_core_db -h localhost -p 5432"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - "./volumes/db/data/airelinecoredb:/var/lib/postgresql/data"
    networks:
      - airline-microservice
  flight-ops-db:
    image: postgres:14.1-alpine
    container_name: flight-ops-db
    mem_reservation: 256m
    mem_limit: 512m
    cpus: 0.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=yt_airline_flight_db
    ports:
      - '3304:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yt_airline_flight_db -h localhost -p 5432"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - "./volumes/db/data/flightopsdb:/var/lib/postgresql/data"
    networks:
      - airline-microservice
  location-db:
    image: postgres:14.1-alpine
    container_name: location-db
    mem_reservation: 256m
    mem_limit: 512m
    cpus: 0.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=yt_airline_location_db
    ports:
      - '3305:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yt_airline_location_db -h localhost -p 5432"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - "./volumes/db/data/locationdb:/var/lib/postgresql/data"
    networks:
      - airline-microservice
  seat-db:
    image: postgres:14.1-alpine
    container_name: seat-db
    mem_reservation: 256m
    mem_limit: 512m
    cpus: 0.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=yt_airline_seat_db
    ports:
      - '3306:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yt_airline_seat_db -h localhost -p 5432"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - "./volumes/db/data/seatdb:/var/lib/postgresql/data"
    networks:
      - airline-microservice
  pricing-db:
    image: postgres:14.1-alpine
    container_name: pricing-db
    mem_reservation: 256m
    mem_limit: 512m
    cpus: 0.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=yt_airline_pricing_db
    ports:
      - '3307:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yt_airline_pricing_db -h localhost -p 5432"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - "./volumes/db/data/pricingdb:/var/lib/postgresql/data"
    networks:
      - airline-microservice
  ancillary-db:
    image: postgres:14.1-alpine
    container_name: ancillary-db
    mem_reservation: 256m
    mem_limit: 512m
    cpus: 0.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=yt_airline_ancillary_db
    ports:
      - '3308:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yt_airline_ancillary_db -h localhost -p 5432"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - "./volumes/db/data/ancillarydb:/var/lib/postgresql/data"
    networks:
      - airline-microservice
  booking-db:
    image: postgres:14.1-alpine
    container_name: booking-db
    mem_reservation: 256m
    mem_limit: 512m
    cpus: 0.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=yt_airline_booking_db
    ports:
      - '3309:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yt_airline_booking_db -h localhost -p 5432"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - "./volumes/db/data/bookingdb:/var/lib/postgresql/data"
    networks:
      - airline-microservice
  payment-db:
    image: postgres:14.1-alpine
    container_name: payment-db
    mem_reservation: 256m
    mem_limit: 512m
    cpus: 0.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=yt_airline_payment_db
    ports:
      - '3310:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yt_airline_payment_db -h localhost -p 5432"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - "./volumes/db/data/paymentdb:/var/lib/postgresql/data"
    networks:
      - airline-microservice
  kafka:
    image: apache/kafka:4.2.0
    container_name: kafka
    hostname: kafka
    mem_limit: 1g
    mem_reservation: 512m
    cpus: 1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAKFA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAT_OPTS: "-Xms256m -Xmx1g"
    networks:
      - airline-microservice
  redis:
    image: redis:7.2-alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru --save ""
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - airline-microservice

  config-server:
    image: kartik9555/config-server:1.0-SNAPSHOT
    container_name: config-server
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "8888:8888"
    depends_on:
      service-registry:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/Kartik9555/airline-config
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - airline-microservice
  service-registry:
    image: kartik9555/service-registry:1.0-SNAPSHOT
    container_name: service-registry
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=service-registry
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx384m -XX:+UseG1GC
      - EUREKA_INSTANCE_HOSTNAME=service-registry
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - airline-microservice
  user-service:
    image: kartik9555/user-service:1.0-SNAPSHOT
    container_name: user-service
    ports:
      - "5001:5001"
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      user-db:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx384m -XX:+UseG1GC
    networks:
      - airline-microservice
  airline-core-service:
    image: kartik9555/airline-core-service:1.0-SNAPSHOT
    container_name: airline-core-service
    ports:
      - "5002:5002"
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      aireline-core-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
        - SPRING_APPLICATION_NAME=airline-core-service
        - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
        - SPRING_PROFILES_ACTIVE=prod
        - SPRING_DATASOURCE_URL=jdbc:postgresql://aireline-core-db:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=admin
        - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
        - SPRING_DATA_REDIS_HOST=redis
        - SPRING_DATA_REDIS_PORT=6379
        - JAVA_TOOL_OPTIONS=-Xms128m -Xmx384m -XX:+UseG1GC
    networks:
      - airline-microservice
  flight-ops-service:
    image: kartik9555/flight-ops-service:1.0-SNAPSHOT
    container_name: flight-ops-service
    ports:
      - "5005:5005"
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      flight-ops-db:
        condition: service_healthy
#      redis:
#        condition: service_healthy
      kafka:
        condition: service_started
    environment:
        - SPRING_APPLICATION_NAME=flight-ops-service
        - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
        - SPRING_PROFILES_ACTIVE=prod
        - SPRING_DATASOURCE_URL=jdbc:postgresql://flight-ops-db:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=admin
        - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
        - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#        - SPRING_DATA_REDIS_HOST=redis
#        - SPRING_DATA_REDIS_PORT=6379
        - JAVA_TOOL_OPTIONS=-Xms128m -Xmx384m -XX:+UseG1GC
    networks:
      - airline-microservice
  location-service:
    image: kartik9555/location-service:1.0-SNAPSHOT
    container_name: location-service
    ports:
      - "5004:5004"
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      location-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
        - SPRING_APPLICATION_NAME=location-service
        - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
        - SPRING_PROFILES_ACTIVE=prod
        - SPRING_DATASOURCE_URL=jdbc:postgresql://location-db:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=admin
        - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
        - SPRING_DATA_REDIS_HOST=redis
        - SPRING_DATA_REDIS_PORT=6379
        - JAVA_TOOL_OPTIONS=-Xms128m -Xmx384m -XX:+UseG1GC
    networks:
      - airline-microservice
  seat-service:
    image: kartik9555/seat-service:1.0-SNAPSHOT
    container_name: seat-service
    ports:
      - "5006:5006"
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      seat-db:
        condition: service_healthy
#      redis:
#        condition: service_healthy
      kafka:
        condition: service_started
    environment:
        - SPRING_APPLICATION_NAME=seat-service
        - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
        - SPRING_PROFILES_ACTIVE=prod
        - SPRING_DATASOURCE_URL=jdbc:postgresql://seat-db:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=admin
        - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
        - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#        - SPRING_DATA_REDIS_HOST=redis
#        - SPRING_DATA_REDIS_PORT=6379
        - JAVA_TOOL_OPTIONS=-Xms128m -Xmx384m -XX:+UseG1GC
    networks:
      - airline-microservice
  pricing-service:
    image: kartik9555/pricing-service:1.0-SNAPSHOT
    container_name: pricing-service
    ports:
      - "5003:5003"
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      pricing-db:
        condition: service_healthy
#      redis:
#        condition: service_healthy
    environment:
        - SPRING_APPLICATION_NAME=pricing-service
        - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
        - SPRING_PROFILES_ACTIVE=prod
        - SPRING_DATASOURCE_URL=jdbc:postgresql://pricing-db:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=admin
        - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
#        - SPRING_DATA_REDIS_HOST=redis
#        - SPRING_DATA_REDIS_PORT=6379
        - JAVA_TOOL_OPTIONS=-Xms128m -Xmx384m -XX:+UseG1GC
    networks:
      - airline-microservice

  ancillary-service:
    image: kartik9555/ancillary-service:1.0-SNAPSHOT
    container_name: ancillary-service
    ports:
      - "5007:5007"
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      ancillary-db:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=ancillary-service
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ancillary-db:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx384m -XX:+UseG1GC
    networks:
      - airline-microservice
  booking-service:
    image: kartik9555/booking-service:1.0-SNAPSHOT
    container_name: booking-service
    ports:
      - "5008:5008"
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      booking-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - SPRING_APPLICATION_NAME=booking-service
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://booking-db:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx384m -XX:+UseG1GC
    networks:
      - airline-microservice
  payment-service:
    image: kartik9555/payment-service:1.0-SNAPSHOT
    container_name: payment-service
    ports:
      - "5009:5009"
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      payment-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - SPRING_APPLICATION_NAME=payment-service
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment-db:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx384m -XX:+UseG1GC
    networks:
      - airline-microservice
  api-gateway:
    image: kartik9555/api-gateway:1.0-SNAPSHOT
    container_name: api-gateway
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    ports:
      - "6000:6000"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx384m -XX:+UseG1GC
    networks:
      - airline-microservice
  notification-service:
    image: kartik9555/notification-service:1.0-SNAPSHOT
    container_name: notification-service
    ports:
      - "5010:5010"
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx384m -XX:+UseG1GC
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - airline-microservice

volumes:
  db:
    driver: local


