server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Kartik9555/airline-config
          clone-on-start: true
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 20
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 10
    disable-delta: false   # keep delta enabled for performance
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
